#NUMPY

In [1]:
import numpy as np
from time import process_time

In [2]:
list1 = [i for i in range(100000000)]
start_time = process_time()

list1 = [i+5 for i in list1]
end_time = process_time()
print(end_time - start_time)

8.478799839999999


In [3]:
np_array = np.array([i for i in range(100000000)])
start_time = process_time()
np_array += 5   
end_time = process_time()
print(end_time - start_time)

0.07458169699999928


DECLERATION OF ARRAY


In [4]:
a = np.array([1,2,3,4])
print(a)
type(a)

[1 2 3 4]


numpy.ndarray

In [5]:
a.shape #used to represent the dimension of the array

(4,)

In [6]:
b = np.array([(1,2,3,4),(5,6,7,8)])    #represented as two dimesional array
print(b)
type(b)
b.shape               # will be treated as 2x4 matrix

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [7]:
c= np.array([(1,2,3,4.5),(5,6,7,8)],dtype=float)

In [8]:
print(c)

[[1.  2.  3.  4.5]
 [5.  6.  7.  8. ]]


#initial placeholders in numpy array

In [9]:
# if we need any particular initial value 
# example - create an array with zero 
x = np.zeros((4,5),dtype = int)
print(x)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [10]:
y= np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
z = np.full((5,4),5)      # to create an array with any particular value (example here is 5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [12]:
a = np.eye(4,dtype = int)      #create an identity matrix
print(a)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [13]:
# create an array using random values 
r = np.random.random((3,4))
print(r)
# Here the values printed are between 1 and 0 

[[0.43810806 0.87232956 0.91268027 0.31919268]
 [0.3139476  0.58628184 0.9078504  0.42949193]
 [0.17068076 0.4443497  0.54505244 0.06470997]]


In [14]:
# Create an array for random value between any two particular values
r = np.random.randint(10,100,(3,4))         #np.random.randint(low,high,size,dtype)
print(r)

[[37 80 84 69]
 [73 12 82 97]
 [87 18 30 81]]


In [15]:
#array of evenly spaced numbers
d= np.linspace(10,30,5,dtype = int)             #np.linspace(start,stop,no_of_value)
print(d)

[10 15 20 25 30]


In [16]:
#array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)      #np.arange(start,stop,step)
print(e)

[10 15 20 25]


In [17]:
#convert a list to an array
list2= [1,2,3,4,5]
arr =  np.asarray(list2)
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

#Analysing a numpy array


In [18]:
c = np.random.randint(10,90,(5,5))
print(c)

[[70 23 61 77 35]
 [28 22 86 30 22]
 [66 54 42 41 18]
 [34 58 74 54 64]
 [13 58 21 74 64]]


In [19]:
#array dimesion
print(c.shape)

(5, 5)


In [20]:
c.shape

(5, 5)

In [21]:
#number of dimensions
print(c.ndim)

2


In [22]:
#number of elements in an array
print(c.size)

25


In [23]:
#checking the data type of the values of the array
print(c.dtype)      #it is showing 64 bit int

int64


#Mathematical operations on a Numpy array


In [24]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1+list2)       # it concatenate or joins two list 

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [25]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(a+b)

[ 7  9 11 13 15]


In [26]:
a = np.random.randint(10,30,(3,3))
b = np.random.randint(20,30,(3,3))
print(a)
print(" ")
print(b)
print(" ")
print(a+b)

[[13 13 22]
 [14 29 16]
 [20 27 15]]
 
[[27 27 29]
 [21 25 23]
 [26 26 29]]
 
[[40 40 51]
 [35 54 39]
 [46 53 44]]


In [27]:
print(a*b)     #it will perform the element wise multiplication

[[351 351 638]
 [294 725 368]
 [520 702 435]]


In [28]:
print(a-b)

[[-14 -14  -7]
 [ -7   4  -7]
 [ -6   1 -14]]


In [29]:
print(np.add(a,b))

[[40 40 51]
 [35 54 39]
 [46 53 44]]


In [30]:
c = np.random.randint(0,50,(3,3))
print(c)

[[27 43 19]
 [ 9 39 19]
 [ 3 45 32]]


In [31]:
print(np.add(a,b,c))

[[40 40 51]
 [35 54 39]
 [46 53 44]]


#ARRAY MANIPULATION

In [32]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 7 1]
 [4 6 3]]
(2, 3)


In [33]:
#transpose of the array
trans = np.transpose(array)

In [34]:
print(trans)

[[1 4]
 [7 6]
 [1 3]]


In [35]:
trans.shape

(3, 2)

In [36]:
#reshaping array
a = np.random.randint(0,10,(2,3))
print(a)
a.shape

[[6 8 6]
 [7 9 5]]


(2, 3)

In [37]:
b = a.reshape(3,2)

In [38]:
print(b)

[[6 8]
 [6 7]
 [9 5]]
