In [ ]:
import numpy as np

In [ ]:
l = [1,2,3,4]


In [ ]:
arr = np.array(l)

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
np.asarray(l)

array([1, 2, 3, 4])

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [ ]:
mat = np.matrix(l)

In [ ]:
np.array(l)

array([1, 2, 3, 4])

In [ ]:
arr[0] = 100

In [ ]:
arr

array([100,   2,   3,   4])

In [ ]:
b = np.copy(arr)

In [ ]:
b[0] = 20

In [ ]:
b

array([20,  2,  3,  4])

In [ ]:
arr

array([100,   2,   3,   4])

In [ ]:
np.fromfunction(lambda i,j: i==j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
np.fromfunction(lambda i,j: i*j ,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
a = (i*i for i in range(5))

In [ ]:
np.fromiter(a,int)

array([ 0,  1,  4,  9, 16])

In [ ]:
m = np.fromstring("23 45 67 ",sep = " ")

In [ ]:
arr

array([100,   2,   3,   4])

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1.ndim  #gives the number of dimension in of an array

2

In [ ]:
arr.size

4

In [ ]:
arr1.size

6

In [ ]:
arr.shape

(4,)

In [ ]:
arr1.shape

(2, 3)

In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [ ]:
np.arange(0.4,10.4,0.2)

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2])

In [ ]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [ ]:
np.logspace(1,5,10,base = 2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [ ]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((3,4,2,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [ ]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
np.ones(5,int)

array([1, 1, 1, 1, 1])

In [ ]:
arr3 = np.ones ((3,4))

In [ ]:
arr3*3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [ ]:
np.empty((3,4))

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
array = np.eye(4,4)

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(array)

0    1    2    3
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  0.0  1.0

In [ ]:
np.random.rand(2,3)

array([[0.73030997, 0.08956929, 0.6390199 ],
       [0.30446678, 0.70726735, 0.27624879]])

In [ ]:
np.random.randn(2,3)           #it will return an array where it gives data following standard normal distribution i.e mean is 0 and standard deviation is 1

array([[ 0.02485078,  0.06524513, -0.20333006],
       [ 0.28578273, -0.92974944,  1.10370648]])

In [ ]:
array1 = np.random.randint(1,100,(3,4))   #3,4 is shape and data is between 1 to 100

In [ ]:
array1

array([[90, 38, 39, 90],
       [41, 65, 78, 55],
       [99, 64, 40, 94]])

In [ ]:
array1.shape

(3, 4)

In [ ]:
array1.reshape(4,3)

array([[90, 38, 39],
       [90, 41, 65],
       [78, 55, 99],
       [64, 40, 94]])

In [ ]:
array1.reshape(6,2)

array([[90, 38],
       [39, 90],
       [41, 65],
       [78, 55],
       [99, 64],
       [40, 94]])

In [ ]:
array1.reshape(2,6)

array([[90, 38, 39, 90, 41, 65],
       [78, 55, 99, 64, 40, 94]])

In [ ]:
array1.reshape(2,-5)

array([[90, 38, 39, 90, 41, 65],
       [78, 55, 99, 64, 40, 94]])

In [ ]:
array1.reshape(2,3,2)

array([[[90, 38],
        [39, 90],
        [41, 65]],

       [[78, 55],
        [99, 64],
        [40, 94]]])

In [ ]:
array1.reshape(2,2,3)

array([[[90, 38, 39],
        [90, 41, 65]],

       [[78, 55, 99],
        [64, 40, 94]]])

In [ ]:
array2 = np.random.randint(1,10,(5,6))

In [ ]:
array2

array([[7, 4, 9, 7, 7, 1],
       [6, 8, 5, 7, 5, 5],
       [3, 4, 9, 6, 1, 4],
       [8, 2, 1, 5, 7, 4],
       [1, 3, 1, 4, 5, 7]])

In [ ]:
array2>5

array([[ True, False,  True,  True,  True, False],
       [ True,  True, False,  True, False, False],
       [False, False,  True,  True, False, False],
       [ True, False, False, False,  True, False],
       [False, False, False, False, False,  True]])

In [ ]:
array2[array2>5]

array([7, 9, 7, 7, 6, 8, 7, 9, 6, 8, 7, 7])

In [ ]:
array2

array([[7, 4, 9, 7, 7, 1],
       [6, 8, 5, 7, 5, 5],
       [3, 4, 9, 6, 1, 4],
       [8, 2, 1, 5, 7, 4],
       [1, 3, 1, 4, 5, 7]])

In [ ]:
array2[0,[0,1]]    #used to extract data at position 0 and 1

array([7, 4])

In [ ]:
array2[2:4,[2,3]]

array([[9, 6],
       [1, 5]])

In [ ]:
array3 = np.random.randint(1,3,(3,3))

In [ ]:
array4 = np.random.randint(1,3,(3,3))

In [ ]:
array3+array4

array([[4, 4, 4],
       [3, 2, 4],
       [4, 3, 3]])

In [ ]:
array3

array([[2, 2, 2],
       [2, 1, 2],
       [2, 1, 1]])

In [ ]:
array4

array([[2, 2, 2],
       [1, 1, 2],
       [2, 2, 2]])

In [ ]:
array3-array4

array([[ 0,  0,  0],
       [ 1,  0,  0],
       [ 0, -1, -1]])

In [ ]:
array3*array4

array([[4, 4, 4],
       [2, 1, 4],
       [4, 2, 2]])

In [ ]:
m1 = np.matrix(array3)


In [ ]:
m2 = np.matrix(array4)

In [ ]:
m1

matrix([[2, 2, 2],
        [2, 1, 2],
        [2, 1, 1]])

In [ ]:
m2

matrix([[2, 2, 2],
        [1, 1, 2],
        [2, 2, 2]])

In [ ]:
m1*m2

matrix([[10, 10, 12],
        [ 9,  9, 10],
        [ 7,  7,  8]])

In [ ]:
array3@array4  #using @ sign we can get the result directly from the matrix

array([[10, 10, 12],
       [ 9,  9, 10],
       [ 7,  7,  8]])

In [ ]:
array3/0

<ipython-input-191-de9c8c835f93>:1: RuntimeWarning: divide by zero encountered in true_divide
  array3/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

#Numpy Broadcasting

In [ ]:
array5 = np.zeros((3,4))

In [ ]:
array5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
array5+5                                 # called broadcasting i.e broadcast by value of 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
array5+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
b = np.array([[3,4,5]])

In [ ]:
# arr+b will return an error

In [ ]:
b.T

array([[3],
       [4],
       [5]])

In [ ]:
c =  array5+b.T

In [ ]:
np.sqrt(c)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [ ]:
np.log10(c)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [ ]:
np.exp(c)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [ ]:
np.max(c)

5.0

In [ ]:
np.min(a)

1

In [ ]:
np.min(c)

3.0

In [ ]:
c

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

# Array Manipulation

In [ ]:
array6 = np.random.randint(1,10,(4,4))

In [ ]:
array6

array([[9, 7, 1, 5],
       [2, 7, 2, 4],
       [4, 1, 1, 1],
       [8, 9, 7, 3]])

In [ ]:
array6.reshape(8,2)

array([[9, 7],
       [1, 5],
       [2, 7],
       [2, 4],
       [4, 1],
       [1, 1],
       [8, 9],
       [7, 3]])

In [ ]:
array6.T

array([[9, 2, 4, 8],
       [7, 7, 1, 9],
       [1, 2, 1, 7],
       [5, 4, 1, 3]])

In [ ]:
array6.flatten()

array([9, 7, 1, 5, 2, 7, 2, 4, 4, 1, 1, 1, 8, 9, 7, 3])

In [ ]:
np.expand_dims(array6,axis=1)

array([[[9, 7, 1, 5]],

       [[2, 7, 2, 4]],

       [[4, 1, 1, 1]],

       [[8, 9, 7, 3]]])

In [ ]:
data = np.array([[1],[2],[3]])

In [ ]:
np.squeeze(data)   #reduced the number of dimension

array([1, 2, 3])

In [ ]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [ ]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [ ]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [ ]:
np.diag(np.array([1,2,5,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 4]])

# Binary operation

In [ ]:
array7 = np.random.randint(1,10,(3,4))

In [ ]:
array8 = np.random.randint(1,10,(3,4))

In [ ]:
array7

array([[2, 1, 9, 5],
       [1, 7, 8, 9],
       [6, 6, 7, 2]])

In [ ]:
array8

array([[6, 5, 3, 2],
       [4, 6, 8, 5],
       [6, 3, 1, 1]])

In [ ]:
array7+array8

array([[ 8,  6, 12,  7],
       [ 5, 13, 16, 14],
       [12,  9,  8,  3]])

In [ ]:
array7-array8


array([[-4, -4,  6,  3],
       [-3,  1,  0,  4],
       [ 0,  3,  6,  1]])

In [ ]:
array7*array8

array([[12,  5, 27, 10],
       [ 4, 42, 64, 45],
       [36, 18,  7,  2]])

In [ ]:
array7/array8

array([[0.33333333, 0.2       , 3.        , 2.5       ],
       [0.25      , 1.16666667, 1.        , 1.8       ],
       [1.        , 2.        , 7.        , 2.        ]])

In [ ]:
array7**array8

array([[      64,        1,      729,       25],
       [       1,   117649, 16777216,    59049],
       [   46656,      216,        7,        2]])

In [ ]:
~array7

array([[ -3,  -2, -10,  -6],
       [ -2,  -8,  -9, -10],
       [ -7,  -7,  -8,  -3]])

In [ ]:
~array8

array([[-7, -6, -4, -3],
       [-5, -7, -9, -6],
       [-7, -4, -2, -2]])

In [ ]:
array7>array8

array([[False, False,  True,  True],
       [False,  True, False,  True],
       [False,  True,  True,  True]])

# String operation

In [ ]:
arr = np.array(["tushar","kumar"])

In [ ]:
arr

array(['tushar', 'kumar'], dtype='<U6')

In [ ]:
np.char.upper(arr)

array(['TUSHAR', 'KUMAR'], dtype='<U6')

In [ ]:
np.char.capitalize(arr)

array(['Tushar', 'Kumar'], dtype='<U6')

In [ ]:
np.char.title(arr)

array(['Tushar', 'Kumar'], dtype='<U6')

# Numpy array mathematical function

In [ ]:
array1

array([[90, 38, 39, 90],
       [41, 65, 78, 55],
       [99, 64, 40, 94]])

In [ ]:
np.sin(array1)

array([[ 0.89399666,  0.29636858,  0.96379539,  0.89399666],
       [-0.15862267,  0.82682868,  0.51397846, -0.99975517],
       [-0.99920683,  0.92002604,  0.74511316, -0.24525199]])

In [ ]:
np.cos(array1)

array([[-0.44807362,  0.95507364,  0.26664293, -0.44807362],
       [-0.98733928, -0.56245385, -0.85780309,  0.02212676],
       [ 0.03982088,  0.39185723, -0.66693806,  0.96945937]])

In [ ]:
np.tan(array1)

array([[ -1.99520041,   0.31030966,   3.61455441,  -1.99520041],
       [  0.1606567 ,  -1.47003826,  -0.59918   , -45.18308791],
       [-25.09253498,   2.34786031,  -1.11721493,  -0.2529781 ]])

In [ ]:
np.tanh(array1)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.log(array1)

array([[4.49980967, 3.63758616, 3.66356165, 4.49980967],
       [3.71357207, 4.17438727, 4.35670883, 4.00733319],
       [4.59511985, 4.15888308, 3.68887945, 4.54329478]])

In [ ]:
np.exp(array1)

array([[1.22040329e+39, 3.18559318e+16, 8.65934004e+16, 1.22040329e+39],
       [6.39843494e+17, 1.69488924e+28, 7.49841700e+33, 7.69478527e+23],
       [9.88903032e+42, 6.23514908e+27, 2.35385267e+17, 6.66317622e+40]])

In [ ]:
np.power(array1,2)

array([[8100, 1444, 1521, 8100],
       [1681, 4225, 6084, 3025],
       [9801, 4096, 1600, 8836]])

In [ ]:
np.mean(array1)

66.08333333333333

In [ ]:
np.std(array1)

22.56272122082992

In [ ]:
np.median(array2)

5.0

In [ ]:
np.var(array2)

5.915555555555556

In [ ]:
np.min(array1)

38

In [ ]:
np.max(array2)

9

In [ ]:
array1 

array([[90, 38, 39, 90],
       [41, 65, 78, 55],
       [99, 64, 40, 94]])

In [ ]:
array2

array([[7, 4, 9, 7, 7, 1],
       [6, 8, 5, 7, 5, 5],
       [3, 4, 9, 6, 1, 4],
       [8, 2, 1, 5, 7, 4],
       [1, 3, 1, 4, 5, 7]])

In [ ]:
array7-array8

array([[-4, -4,  6,  3],
       [-3,  1,  0,  4],
       [ 0,  3,  6,  1]])

In [ ]:
np.subtract(array7,array8)

array([[-4, -4,  6,  3],
       [-3,  1,  0,  4],
       [ 0,  3,  6,  1]])

In [ ]:
np.multiply(array7,array8)

array([[12,  5, 27, 10],
       [ 4, 42, 64, 45],
       [36, 18,  7,  2]])

In [ ]:
np.mod(array7,array8)

array([[2, 1, 0, 1],
       [1, 1, 0, 4],
       [0, 0, 0, 0]])

In [ ]:
np.power(array7,array8)

array([[      64,        1,      729,       25],
       [       1,   117649, 16777216,    59049],
       [   46656,      216,        7,        2]])

In [ ]:
np.sqrt(array7)

array([[1.41421356, 1.        , 3.        , 2.23606798],
       [1.        , 2.64575131, 2.82842712, 3.        ],
       [2.44948974, 2.44948974, 2.64575131, 1.41421356]])

In [ ]:
np.sqrt(array8)

array([[2.44948974, 2.23606798, 1.73205081, 1.41421356],
       [2.        , 2.44948974, 2.82842712, 2.23606798],
       [2.44948974, 1.73205081, 1.        , 1.        ]])

In [ ]:
np.std(array7)

2.890357532670771

In [ ]:
np.mean(array8)

4.166666666666667

In [ ]:
from scipy import stats as st

In [ ]:
st.mode(array7)

<ipython-input-292-f540ac246178>:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  st.mode(array7)


ModeResult(mode=array([[1, 1, 7, 2]]), count=array([[1, 1, 1, 1]]))

In [ ]:
arr = np.array([6,5,4,3,2,1])

In [ ]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr2 = np.array([1,2,3,4,5])

In [ ]:
np.searchsorted(arr,6)

6

In [ ]:
arr3 = np.array([0,234,543,654,234,54,876,43])

In [ ]:
np.count_nonzero(arr3)

7

In [ ]:
arr3.size

8

In [ ]:
np.where(arr3>234)

(array([2, 3, 6]),)

In [ ]:
import numpy.matlib as nm

In [ ]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [ ]:
nm.ones(5)

matrix([[1., 1., 1., 1., 1.]])

In [ ]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
arr

array([6, 5, 4, 3, 2, 1])

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])